name: AutomacaoSpinnaker

on:
  workflow_dispatch:

jobs:
  copy-files:
    name: Copy files TF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: terraform
          path: ${{ github.workspace }}//spinnaker
  create-pipeline:
    name: Create pipeline spinnaker
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ${{ github.workspace }}/spinnaker
        
    environment:
      name: dev
    
    needs: copy-files
    
    steps:
      - name: Download Terraform
        uses: actions/download-artifact@v2
        with:
          name: terraform
          path: ${{ github.workspace }}//spinnaker
      
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init
        
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
        
      - name: Terraform Apply
        run: terraform apply -auto-approve
        continue-on-error: true
      
     
    

    
